### ISSUE TITLE
Game update made it unusable

### ISSUE THREAD

**Issue by kuyi843** [calamity-inc/Stand-for-FH5#1]
Can't detect game running, it's a very useful tool, I hope you can keep updating

**Comment by Sainan** [comment]
Updated

**Comment by VerusLucian** [comment]
Go to your game installation folder and change the name of executable from forzahorizon5.exe to **F**orza**H**orizon5.exe This can help you.

**Comment by VerusLucian** [comment]
> Go to your game installation folder and change the name of executable from forzahorizon5.exe to **F**orza**H**orizon5.exe This can help you.

I was one minute late :) as author sad it has been fixed.

**Comment by kuyi843** [comment]
I don't know how to operate it @VerusLucian

**Comment by kuyi843** [comment]
Thank you so much, now it works perfectly again @VerusLucian @Sainan

**Comment by kuyi843** [comment]
Thank you so much, now it works perfectly again @VerusLucian @Sainan
