### ISSUE TITLE
autoshowAllfree() exists game process

### ISSUE THREAD

**Issue by VerusLucian** [calamity-inc/Stand-for-FH5#2]
After some debugging it seems that this option doesn't work well after recent updates.
I'm using the steam version of the game but testing in on other device with XboxPass is working correctly.

Steps to reproduce:

1. Start game
2. Start the executable
3. Choose option "Shown" from combo box (or any other)
4. Then click "Make All Cars Free" button
5. Game freezes go to auto show in game after few seconds game process ends

**Comment by Sainan** [comment]
Can reproduce, although it's unclear to me why it happens, as the SQL query being hijacked seems unchanged since I last dumped the game

**Comment by Sainan** [comment]
Hmm, it seems externalWrite is failing with "Invalid access to memory location."
