### ISSUE TITLE
Credits doesnt seem to stick

### ISSUE THREAD

**Issue by IrcDirk** [calamity-inc/Stand-for-FH5#3]
Changing Credits doesn't seem to stick on Ms Store version. When u unlock it goes to previous number.

Worked on some previous version from stand.gg site.

**Comment by Sainan** [comment]
Works as "intended". You'll have to modify your credits for it to stick.

**Comment by IrcDirk** [comment]
Tired to buy a car, wheelspin with credits price...after unlocking it goes back every time. Maybe im doing something wrong @Sainan give me an example.

**Comment by Sainan** [comment]
I'm on the Steam version (not that I play much anymore), and this project isn't being actively maintained, so take it "as-is."

**Comment by IrcDirk** [comment]
U should disable Issues on the repo ;)
